### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by alexanderadam** [iTXTech/Daedalus#45]
it would be wonderful if Daedalus could be published in the official repositories [on F-Droid](https://f-droid.org/packages/).

Thank you in advance!

**Comment by PeratX** [comment]
Let me see.

**Comment by alexanderadam** [comment]
Oh, what a pity. But thank you for answering and having a look on it. 👍

**Comment by PeratX** [comment]
You are welcome. If have further questions, you can contact me immediately.

**Comment by eighthave** [comment]
Just a small point of clarification: the play-services plugin is proprietary and the source code is not available.  No one but Google can build it.

**Comment by PeratX** [comment]
Maybe I will consider it again xD

**Comment by eighthave** [comment]
there are many apps built in F-Droid where there is a special "free
software" build flavor that builds the app without any proprietary
blobs.  Often it is possible to just patch out the proprietary libraries
in the fdroid build process.

There was already a request to package (RFP) this in fdroid:
https://gitlab.com/fdroid/rfp/issues/165

**Comment by beerisgood** [comment]
Anybody can confirm that?: https://github.com/privacytoolsIO/privacytools.io/issues/533#issuecomment-429233570

**Comment by PeratX** [comment]
I got it. What about a separated branch without Firebase and Fabric?
I use Firebase for analyzing crash information because Daedalus is my first Android App. ;)

**Comment by eighthave** [comment]
A separate branch is one possibility.  Another is using free software for crash reports and analytics.  ACRA is a free software crash reporter.  Then you wouldn't need a separate branch for F-Droid.

**Comment by IzzySoft** [comment]
It would be great if you had at least a branch that comes without Crashlytics and Firebase Analytics. A VPN app shouldn't come with trackers (otherwise it's a contradiction: you don't "securely tunnel" and then have something "report to 3rd parties" from inside – even if we'd trust the dev, not even the dev can tell for sure what those closed-source modules really do).

I fully agree with Hans, replacing the two proprietary trackers with an open source one like ACRA or Matomo would be much preferred – even better if the app can live without. At least in a branch for F-Droid, if not in general 😃 

Any chance for that, @PeratX?

**Comment by PeratX** [comment]
@IzzySoft I will do it. After I have time (July maybe, or you could just submit a pull request)

**Comment by IzzySoft** [comment]
Great, thanks @PeratX – then we'll wait for July. I'm no dev, so I unfortunately cannot help out with a PR…

**Comment by Rsplwe** [comment]
@IzzySoft

**Comment by PeratX** [comment]
https://github.com/iTXTech/Daedalus/tree/without-google
almost done.

**Comment by PeratX** [comment]
ok. I've added `pure` build config. I will handle it to fdroid some time later.
